{{- if and .Values.prometheus.jmx.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-metrics-servicemonitor
  # Change this to the namespace the Prometheus instance is running in
  # namespace: default
  labels:
    app: {{ template "cp-kafka.name" . }}
    chart: {{ template "cp-kafka.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "cp-kafka.name" . }}
      chart: {{ template "cp-kafka.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  endpoints:
  - port: jmx
    interval: 15s
{{- end }}
